### PR TITLE
fix import siwe index

### LINKED ISSUE #251: [bug]: Siwe config module import
### Description

I'm using reown in my Expo/ React native app.

I'm getting an issue when using the siwe

Unable to resolve "../src/client" from "../../node_modules/.pnpm/@reown+appkit-siwe-react-native@1.0.0_6fyeilfofzxrb2fsgksfqkrszq/node_modules/@reown/appkit-siwe-react-native/lib/module/index.js"

### AppKit SDK version

@reown/appkit-siwe-react-native 1.0.0

### Output of `npx react-native info`

System:
  OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
  CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Memory: 10.52 GB / 19.31 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 22.9.0
    path: /usr/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.3
    path: /usr/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Expo Version (if applies)

_No response_

### Steps to reproduce

Create an EVM Providers with reown.

I'm using the SiweConfig as the example in your repo/docs.

The error occurs when we use this EVMProviders context with SiweConfig.

At the moment, we have created a direct patch of the import in the siwe lib for our prod app.

### Snack, code example, screenshot, or link to a repository

https://github.com/AFK-AlignedFamKernel/afk_monorepo/blob/main/apps/mobile/src/app/EVMProvider.tsx

### PR DESCRIPTION
**Pull request by MSghais**
# Description 

Close #251 issue reported. 
Client imports fixed in the index.ts of the Siwe package

### CODE REVIEW

**Comment by MSghais** [comment]
Blocking the development of my app with the new lib. 

Hope it can be fast merged @chris13524 @bkrem @skibitsky @m1heng please

**Comment by ignaciosantise** [comment]
hey @MSghais 👋 i guess this only happens with PNPM? i didn't encounter this issue using NPM/Yarn 🤔 

anyways, im working on another patch, so i'll include this change there too

**Comment by MSghais** [comment]
Oh yes maybe this is only on pnpm, didn't check with others package manger. But when I've forked the repo, the path of the client is not in src/ but in the root of the index.ts. That's explain my issue atm

**Comment by ignaciosantise** [comment]
released in v1.0.1 🎉

**Pull request closed without merging**
